
[functions.debug-drive]
enabled = true
verify_jwt = true
import_map = "./functions/debug-drive/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/debug-drive/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/debug-drive/*.html" ]

[functions.upload-drive-file]
enabled = true
verify_jwt = true
import_map = "./functions/upload-drive-file/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload-drive-file/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload-drive-file/*.html" ]

[functions.migrate-drive-photos]
enabled = true
verify_jwt = true
import_map = "./functions/migrate-drive-photos/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/migrate-drive-photos/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/migrate-drive-photos/*.html" ]

[functions.repair-drive]
enabled = true
verify_jwt = true
import_map = "./functions/repair-drive/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/repair-drive/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/repair-drive/*.html" ]

[functions.material-assistant-chat]
enabled = true
verify_jwt = true
import_map = "./functions/material-assistant-chat/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/material-assistant-chat/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/material-assistant-chat/*.html" ]
