-- ネグロス電工 カタログ自動抽出SQLデータ


-- ネグロス電工 : /Users/hasuiketomoo/Downloads/catalog_densetsu-kai.pdf のデータ
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR30', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。電線管やケーブルを支持するための直線タイプのケーブルラックです。溶融亜鉛めっき仕上げ。', 3500, NULL, 'https://drive.google.com/file/d/1beHW2kqNS-zzFjJOU1MWKsSvJWfSiYHB/view?usp=drive_link#page=136', 300, 100, NULL, 136);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR40', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。電線管やケーブルを支持するための直線タイプのケーブルラックです。溶融亜鉛めっき仕上げ。', 4200, NULL, 'https://drive.google.com/file/d/1beHW2kqNS-zzFjJOU1MWKsSvJWfSiYHB/view?usp=drive_link#page=136', 400, 100, NULL, 136);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SRF30', 'SRタイプ 90°曲りラック', 'ケーブルラック関連部材。水平方向の90度方向転換に使用するケーブルラックです。溶融亜鉛めっき仕上げ。', 7500, NULL, 'https://drive.google.com/file/d/1beHW2kqNS-zzFjJOU1MWKsSvJWfSiYHB/view?usp=drive_link#page=136', 300, 100, NULL, 136);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SRF40', 'SRタイプ 90°曲りラック', 'ケーブルラック関連部材。水平方向の90度方向転換に使用するケーブルラックです。溶融亜鉛めっき仕上げ。', 9000, NULL, 'https://drive.google.com/file/d/1beHW2kqNS-zzFjJOU1MWKsSvJWfSiYHB/view?usp=drive_link#page=136', 400, 100, NULL, 136);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SRT30', 'SRタイプ 水平T形ラック', 'ケーブルラック関連部材。水平方向の分岐に使用するケーブルラックです。溶融亜鉛めっき仕上げ。', 12000, NULL, 'https://drive.google.com/file/d/1beHW2kqNS-zzFjJOU1MWKsSvJWfSiYHB/view?usp=drive_link#page=136', 300, 100, NULL, 136);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SRT40', 'SRタイプ 水平T形ラック', 'ケーブルラック関連部材。水平方向の分岐に使用するケーブルラックです。溶融亜鉛めっき仕上げ。', 14500, NULL, 'https://drive.google.com/file/d/1beHW2kqNS-zzFjJOU1MWKsSvJWfSiYHB/view?usp=drive_link#page=136', 400, 100, NULL, 136);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SRX30', 'SRタイプ 水平クロス形ラック', 'ケーブルラック関連部材。水平方向の交差分岐に使用するケーブルラックです。溶融亜鉛めっき仕上げ。', 18000, NULL, 'https://drive.google.com/file/d/1beHW2kqNS-zzFjJOU1MWKsSvJWfSiYHB/view?usp=drive_link#page=136', 300, 100, NULL, 136);

-- ネグロス電工 : /Users/hasuiketomoo/Downloads/catalog_taflock-kai.pdf のデータ
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR30', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅300mm、高さ50mmのSRタイプ直線ラック。', 4290, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 300, 50, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR40', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅400mm、高さ50mmのSRタイプ直線ラック。', 4590, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 400, 50, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR50', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅500mm、高さ50mmのSRタイプ直線ラック。', 4880, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 500, 50, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR60', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅600mm、高さ50mmのSRタイプ直線ラック。', 5170, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 600, 50, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-H30', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅300mm、高さ80mmのSRタイプ直線ラック。', 5170, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 300, 80, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-H40', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅400mm、高さ80mmのSRタイプ直線ラック。', 5530, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 400, 80, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-H50', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅500mm、高さ80mmのSRタイプ直線ラック。', 5900, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 500, 80, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-H60', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅600mm、高さ80mmのSRタイプ直線ラック。', 6260, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 600, 80, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-W10', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅100mm、高さ50mmのSRタイプ直線ラック。', 3880, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 100, 50, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-W15', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅150mm、高さ50mmのSRタイプ直線ラック。', 3990, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 150, 50, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-W20', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅200mm、高さ50mmのSRタイプ直線ラック。', 4090, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 200, 50, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-WH10', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅100mm、高さ80mmのSRタイプ直線ラック。', 4600, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 100, 80, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-WH15', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅150mm、高さ80mmのSRタイプ直線ラック。', 4730, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 150, 80, NULL, 62);
INSERT INTO materials (manufacturer_id, model_number, name, description, standard_price, image_url, catalog_url, width_mm, height_mm, depth_mm, page_number) VALUES ((SELECT id FROM manufacturers WHERE name = 'ネグロス電工' LIMIT 1), 'SR-WH20', 'SRタイプ 直線ラック', 'ケーブルラック関連部材。幅200mm、高さ80mmのSRタイプ直線ラック。', 4860, NULL, 'https://drive.google.com/file/d/1nTR7o4ksXloTWf9nwGWoQUErB6X7LDjS/view?usp=drive_link#page=62', 200, 80, NULL, 62);
